# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4d154f01-95b3-4c8a-9f0e-62a3669cc8ea";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4d154f01-95b3-4c8a-9f0e-62a3669cc8ea".device = "/dev/disk/by-uuid/4d154f01-95b3-4c8a-9f0e-62a3669cc8ea";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F06B-AEA9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3351c4c2-62ea-4f7f-a56f-9aa7c2a49203"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
